from collections.abc import Iterable
from typing import Protocol

class DwarfInfo(Protocol):
    def iter_CUs(self) -> Iterable[object]: ...

    def get_addr(self, cu: object, addr_index: int) -> int: ...

class ELFFile:
    elfclass: int
    little_endian: bool

    def __init__(self, stream: object) -> None: ...

    def iter_sections(self) -> Iterable[object]: ...

    def get_section(self, index: int) -> object: ...

    def has_dwarf_info(self) -> bool: ...

    def get_dwarf_info(self) -> DwarfInfo: ...
